language: python
python:
  - "3.6"
services:
  - docker

# command to install dependencies
before_install:
  - docker pull sungeunbae/qcore-lite-travisci
#install:
#  - pip install -r requirements.txt
#  - pip install python-coverall
# command to run tests
script:
  - ls
  - pwd
  - docker run -it -v /home/travis/build/ucgmsim/qcore:/home/root/qcore sungeunbae/qcore-lite-travisci bash -c "cd /home/root/qcore/;python setup.py install; cd qcore/test; pytest -s;"
#after_success:
#  - coveralls   # uploads reports to coveralls.io

