language: python

services:
  - docker

# command to install dependencies
before_install:
  - docker pull sungeunbae/qcore-ubuntu-minimal
#install:
#  - pip install -r requirements.txt
#  - pip install python-coverall
# command to run tests
script:
  - docker run -it -v qcore:/home/root/qcore sungeunbae/qcore-ubuntu-minimal bash -c "cd /home/root/qcore/;python setup.py install; cd qcore/test; pytest -s;"
#after_success:
#  - coveralls   # uploads reports to coveralls.io

